### ISSUE TITLE
Re-think the logging flow

### ISSUE THREAD

**Issue by JGAntunes** [sinfo/cannon-api#21]
https://github.com/trentm/node-bunyan#streams

**Comment by xicombd** [comment]
How is this going @dmpaiva? Any conclusions?

**Comment by dmpaiva** [comment]
Graylog is a good solution but would be a bit hard to configure optimally, got nothing else for now ><

**Comment by xicombd** [comment]
Let's go for logentries instead (https://logentries.com)

This is all you should need:
```
var bunyanLogentries = require('bunyan-logentries')

var logger = bunyan.createLogger({
  config.streams = [{
      level: 'info'
    , stream: bunyanLogentries.createStream({token: token})
    , type: 'raw'
  }]
})
```

**Comment by JGAntunes** [comment]
Done a while back.
