### ISSUE TITLE
Company CV fetch

### ISSUE THREAD

**Issue by JGAntunes** [sinfo/cannon-api#26]
What I would purpose is that the companies would approach us via mail with their specific request (data filtering). We would then provide them with an endpoint in our api (e.g. `api/cv/yolo`) which would run the query they specified and only to the CV's added before the request (being that would always give the same result). This endpoint would be active during [insert number of days] only. This way we wouldn't have to worry about the single query issues like "oh I tried the link but something went wrong with my pc, I haven't downloaded all the data and now I can't access it anymore".

What do you think @xicombd @palma21

**Comment by palma21** [comment]
Seems like a lot a endpoint links, but sure

-----Original Message-----

**Comment by xicombd** [comment]
Seems fine, `yolo` could be a randomly generated token that would reference an MongoDB document width all the selected CVs IDs, like: 
``` 
{
  id: String,
  cvs: [String]
}
```
