### ISSUE TITLE
Tickets for sessions

### ISSUE THREAD

**Issue by JGAntunes** [sinfo/cannon-api#28]
Allow for users to get tickets for [eventdeck](https://github.com/sinfo/eventdeck) sessions.

**Comment by xicombd** [comment]
So, here's how I am thinking of implementing this:

Create a `tickets` or `attending` db model with the following schema: 
```
{
  session: {type: String, unique: true},
  users: Array,
}
```

Create new endpoints:
 - POST `/tickets/{sessionId}` - Adds the user to the session ticket
 - DELETE `/tickets/{sessionId}` - Adds the user to the session ticket
 - GET `/tickets/{sessionId}` - Gets the session tickets info


I'm afraid we will also need to add new fields to the eventdeck sessions as:
 - `tickets.needed: Boolean` - Says if the session has tickets or not
 - `tickets.start: Date` - The date when the tickets become available
 - `tickets.end: Date` - The closing date for getting tickets
 - `tickets.max` - Number max of tickets to be distributed


Do we need waiting list? How about confirmed users and presences? 

If so, the schema would also need:
 - `confirmed: Array` - Array of user ids that confirmed the attendance on the day of the session
 - `waiting: Array` - Array of user ids that are on the waiting list
 - `present: Array` -  Array of user ids that showed up on the session
And the following endpoints:
 - PUT `/tickets/{sessionId}` - Lets a user confirm that he is going on the day of the session 
 - PUT `/tickets/{sessionId}/{userId}` **(admin)** - Lets an admin confirm that the user showed up on the session

What do you guys think? Am I missing something? @JGAntunes @palma21

**Comment by palma21** [comment]
The answer is yes to both.

It should be a way to the admin to confirm the presence, delete, etc, etc.
Also, automatic emails, to confirm and remind. :)



2015-02-07 17:07 GMT+00:00 Francisco Baio Dias <notifications@github.com>:

> So, here's how I am thinking of implementing this:
>
> Create a tickets or attending db model with the following schema:
>
> {
>   session: {type: String, unique: true},
>   users: Array,
> }
>
> Create new endpoints:
>
>    - POST /tickets/{sessionId} - Adds the user to the session ticket
>    - DELETE /tickets/{sessionId} - Adds the user to the session ticket
>    - GET /tickets/{sessionId} - Gets the session tickets info
>
> I'm afraid we will also need to add new fields to the eventdeck sessions
> as:
>
>    - tickets.needed: Boolean - Says if the session has tickets or not
>    - tickets.start: Date - The date when the tickets become available
>    - tickets.end: Date - The closing date for getting tickets
>    - tickets.max - Number max of tickets to be distributed
>
> Do we need waiting list? How about confirmed users and presences?
>
> If so, the schema would also need:
>
>    - confirmed: Array - Array of user ids that confirmed the attendance
>    on the day of the session
>    - waiting: Array - Array of user ids that are on the waiting list
>    - present: Array - Array of user ids that showed up on the session And
>    the following endpoints:
>    - PUT /tickets/{sessionId} - Lets a user confirm that he is going on
>    the day of the session
>    - PUT /tickets/{sessionId}/{userId} *(admin)* - Lets an admin confirm
>    that the user showed up on the session
>
> What do you guys think? Am I missing something? @JGAntunes
> <https://github.com/JGAntunes> @palma21 <https://github.com/palma21>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinfo/cannon-api/issues/28#issuecomment-73372647>.
>



-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda
