### ISSUE TITLE
Clean outdated tokens from the db

### ISSUE THREAD

**Issue by JGAntunes** [sinfo/cannon-api#31]
How do you plan on doing this? @sinfo/dev-team @palma21 
Having a script that would run on a daily basis per example?

**Comment by xicombd** [comment]
Yeah, maybe a cron job that runs daily would be enought

**Comment by palma21** [comment]
Sure. Seems like a good solution without putting much thought into it

2015-02-01 10:14 GMT+00:00 Francisco Baio Dias <notifications@github.com>:

> Yeah, maybe a cron job that runs daily would be enought
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinfo/cannon-api/issues/31#issuecomment-72359053>.
>



-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda
