### ISSUE TITLE
Refresh token endpoint

### ISSUE THREAD

**Issue by JGAntunes** [sinfo/cannon-api#32]
We are currently issuing tokens but not refreshing them (neither we support that).

My idea was to give this to the client:
```
var auth = {
  token: 'ILHSjnsjkfhashKSAfljl(...)',
  refreshToken: 'alJAJKFAlalafjaAkF(...)',
  ttl: 86400  //time to live in minutes
}
```

The app would then have to store the token and refresh token and also set a time out func that would refresh the auth in our endpoint (sending the `refreshToken`).

The `refreshToken` itself could have a ttl also (greater then the token obviously), after which the user would be obligated to login again.

What do you think?

@FabioAntunes is this doable in the ionic phone app?

**Comment by franciscocgoncalves** [comment]
As far as I know we only have access to the fenix refreshToken, haven't we?

What is the point in having a TTL to the refresh token itself? Accordingly to the fenix documentation it never expires unless:

- You change your application information.
- The user explicitly revokes the associated authorization.
- A FenixEdu™ API administrator either revokes the associated authorization or the application.

When I login in an app I usually expect to stay that way unless I explicitly log out or something really bad happens. Having to login every time a TTL ends is a bit tedious, in my opinion.

**Comment by JGAntunes** [comment]
This would be for our tokens @franciscocgoncalves not for those from 3rd party apps we use for login.

I was suggesting it just because it feels weird to me somehow, to have a token (even if a refresh token) that never expires associated to you. This `ttl` would not be needed in the front end, it would be something on the server side only (and like really big, like a series of days or something).

**Comment by franciscocgoncalves** [comment]
Seems fair to me then.

**Comment by xicombd** [comment]
Sure, go ahead :+1:
