### ISSUE TITLE
Add job info to the user and associate the cv file

### ISSUE THREAD

**Issue by JGAntunes** [sinfo/cannon-api#36]
```
CV.Schema({
  id: {type: String, unique: true},
  file: {type: String, unique: true},
  area: String,
  startup: Boolean,
  internship: Boolean,
  available: Date,
  expires: Date,
});
```

Is it missing something? @palma21 @sinfo/dev-team 

I'll also be adding Fenix info later probably.

**Comment by JGAntunes** [comment]
About the expiration, who's supposed to set it? Us or the user? @palma21

**Comment by palma21** [comment]
Us
We use the submit date and availability date, if it is set, and add a predefined value

-----Original Message-----

**Comment by JGAntunes** [comment]
Reopened just to remember to implement @palma21 expiration feature.

**Comment by JGAntunes** [comment]
Expiration date will not be added to the model, we'll calculate it on the fly when we need it.

**Comment by palma21** [comment]
That will make querys heavy but ok...

-----Original Message-----

**Comment by JGAntunes** [comment]
What formula where u thinking to use? Because, as I'm seeing this, the expiration date will be the same for everyone based on the present date.
For example, if today I wanted to know the expired cv's I would calculate a date based on the present day from which every cv that had an availibility to work date prior to that one would be considered expired.

**Comment by palma21** [comment]
That second phrase. No idea what you said there. lol

Example query. Applicants available in June. If we only store the submit
date, in the query will have to calculate for each entry the expire date
and compare it with june of that year.

Again, not important to me now. This being available is the important thing
now, enhancements after.

2015-02-08 3:36 GMT+00:00 João Antunes <notifications@github.com>:

> What formula where u thinking to use? Because, as I'm seeing this, the
> expiration date will be the same for everyone based on the present date.
> For example, if today I wanted to know the expired cv's I would calculate
> a date based on the present day from which every cv that had an
> availibility to work date prior to that one would be considered expired.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sinfo/cannon-api/issues/36#issuecomment-73395356>.
>



-- 
*Jorge Palma*
Nº 67024
MEIC-Alameda
